### ISSUE TITLE
[CON-88] Incoming idempotent webhooks

### ISSUE THREAD

**Issue by binaryfire** [frain-dev/convoy#1618]
Hi guys

Great project! I'm interested in self hosting the open source version instead of building my own webhook handler, but I can't find any info about idempotent processing of incoming webhooks. If Stripe (for example) sends a webhook twice, would Convoy process it twice?

<sub>[CON-88](https://linear.app/convoy-engineering/issue/CON-88/incoming-idempotent-webhooks)</sub>

**Comment by subomi** [comment]
Thanks @binaryfire , 

You're correct. Convoy will process each event independently. This feature is a little trickier to implement, which is counterintuitive to what I expected. The problem is identifying the idempotent key to use because various providers implement this feature differently, Let's take 3 examples:

1. **Stripe:** The Idempotent key is included in the request body. So you'll need to retrieve the `id` field from the request payload. See the [docs](https://stripe.com/docs/webhooks/best-practices#event-handling).
2. Adyen: The Idempotent key is a combination of `eventCode` and `pspReference`. So we'll need to extract both values and create a unique constraint out of them. See the [docs](https://docs.adyen.com/development-resources/webhooks/best-practices#handling-duplicates).
3. GitHub: The Idempotent key is the HTTP Header: `X-GitHub-Delivery`. See the [docs](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#delivery-headers).

Of all the implementations, GitHub is the easiest to implement; we can open up a form field on the source configuration to specify the header to act as the idempotent key, but this doesn't work for all use cases. I suggest we'll need to implement a "request matching dsl" to match the different patterns to accommodate different provider's idempotency key implementation. 

What do you think?

**Comment by binaryfire** [comment]
@subomi Yeah, I think that makes sense. That would allow you to use any part of the request (headers or specific JSON keys) as the idempotent key.

**Comment by subomi** [comment]
Hey @binaryfire , 

This has shipped in the latest release! And we just launched it [here](https://twitter.com/getconvoy/status/1673620373550530560?s=20)
