### ISSUE TITLE
I have added the database connection details in convoy file and configured but the data is not stored in postgres DB.

### ISSUE THREAD

**Issue by tejaswinit2024** [frain-dev/convoy#1940]
I have added the database connection details in convoy file and configured but the data is not stored in postgres DB.

**Comment by simbwa** [comment]
@tejaswinit2024 Is it possible to share your deployed Convoy  version and the convoy configs?

**Comment by tejaswinit2024** [comment]
Convoy version v0.6.6
As attached above is the convoy config file. Please go through and reply as soon as popssible.

Thanks,
Tejaswini
________________________________

**Comment by jirevwe** [comment]
Hey @tejaswinit2024,

`v0.6.6` is about 2 years old at this point and is based on MongoDB. We have since [moved away](https://docs.getconvoy.io/release-notes/releases#v0-9) from it and replaced it with Postgres. Please review [the documentation](https://docs.getconvoy.io/home/quickstart) and let us know if you have any other issues setting it up.

I will close this issue; please feel free to open another one.
