### ISSUE TITLE
Can't create a project from the UI / Application vs Project

### ISSUE THREAD

**Issue by oyekanmiayo** [frain-dev/convoy#597]
Hi there

I signed up on convoy, and I'm just walking through the UI atm. It looks like I can't create a project on the UI.

<img width="1439" alt="Screenshot 2022-04-13 at 08 21 49" src="https://user-images.githubusercontent.com/26260543/163121951-d11b6083-f9e9-42c8-a32e-f4ae7f304050.png">

There's no `Create` button in the image above, and clicking `Enter` on the keyboard doesn't work either.

Furthermore, the idea of a "project" is a bit confusing to me -- the docs only mention ["application"](https://convoy.readme.io/reference/get_applications). So does "project" in the UI refer to "application" in the docs?

**Comment by horlah** [comment]
Hi @oyekanmiayo. The create button is hidden below the page due to the height of the browser window. Please you can increase the height of your browser window to fix it; we'll work on a fix for this.

Project here == Group on the documentation. 
- Applications inside a project to send webhook events to.
- Project represents your product that sends out webhooks (you might have multiple or multiple environments: dev, staging, prod), which will most likely have different applications listening to webhook events from it.

**Comment by oyekanmiayo** [comment]
Looking at the page on a bigger screen helped - thank you.

Also, thanks for the Project (Group) <> Application clarification, it makes sense to me.

Closing this issue.
