### ISSUE TITLE
Can we delete/edit an endpoint from the dashboard?

### ISSUE THREAD

**Issue by mykeels** [frain-dev/convoy#608]
It does not seem like we can, so we had to delete the App, and recreate it.

**Comment by Subomi** [comment]
Oh. You can't edit/delete endpoints from the dashboard, but you can do it from the API without deleting the App.

**Comment by djperrefort** [comment]
I came across this issue because I had the same question. Are there plans to add dashboard controls for commands (like endpoint management) that are currently only accessible via the API?

As someone who is concerned with enterprise-style deployments, needing to learn a new API instead of having a simple GUI interface is a quick way to eliminate certain types of tools from consideration. Teaching (for example) a system-admin new team how to click a button is a lot easier than teaching them an API.

**Comment by Subomi** [comment]
Hi @djperrefort, thanks for doing a +1 to this issue. 

Yes, there is a plan to add more dashboard controls for everything currently possible over the API.

**Comment by jirevwe** [comment]
Hey guys 👋🏿,

This has been implemented and will be available in the next release which is coming out this weekend.
