### ISSUE TITLE
Endpoint `Secrets` are not being updated

### ISSUE THREAD

**Issue by CreamyMilk** [frain-dev/convoy#639]
Apparently when I update an endpoint's `Secret` Convoy doesn't persist the update.

Demo of the issue 👉 : https://github.com/CreamyMilk/convoy-stuff/blob/main/main.go

**Comment by oneEyedSunday** [comment]
We might probably also want to check if this affects other resources (since it seems we're having to self select which properties get updated on some entities)

**Comment by Subomi** [comment]
This issue was a feature, not a bug. :(  The reasoning was secrets are sensitive things, and we wouldn't want them to be updated "easily". But we didn't add a new API for it (e.g. `PUT /applications/{appID}/endpoints/{endpointID}/secret`), which leaves the user with the last choice of deleting the old app and creating a new one with the new secret -- Not the best solution. 

Thanks for raising the issue & pr.
