### ISSUE TITLE
Docker Auth Credentials

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [frain-dev/convoy#908]
I am having issues with setting up the default docker environmental variables for the username & password. I've searched all of your documentation and the validation code, but I can not find the proper format for the username/passoword for the docker CONVOY_BASIC_AUTH_CONFIG

How should I format that? I've tried every combination I can possibly think of.

**Comment by Subomi** [comment]
Hi @TheBoatyMcBoatFace, 

Yeah, that configuration has been deprecated. But If you're running into this issue because you don't know how to log in when you spin up a new instance, the default login credentials are: 

email: `superuser@default.com`
password: `default`

I think this is missing in our docs. I will update it.
